export { ReactComponent as LogoIcon } from './logo.svg'
export { ReactComponent as ShapeIcon } from './shape.svg'
export { ReactComponent as TelegramIcon } from './telegram.svg'
export { ReactComponent as WhatsappIcon } from './whatsapp.svg'
export { ReactComponent as PhoneIcon } from './phone.svg'
export { ReactComponent as HomeIcon } from './home.svg'
export { ReactComponent as ContactsIcon } from './contacts.svg'
export { ReactComponent as ProcessIcon } from './process.svg'
export { ReactComponent as ServicesIcon } from './services.svg'
export { ReactComponent as TariffsIcon } from './tariffs.svg'

