name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: checkout
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: build project
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

#      - uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: '${{ secrets.GITHUB_TOKEN }}'
#          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUCHEOT }}'
#          projectId: bucheot
